//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.DbFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCartItem
    {
        public System.Guid Id { get; set; }
        public System.Guid ShoppingCartId { get; set; }
        public System.Guid ProductID { get; set; }
        public int Count { get; set; }
    
        public virtual ShoppingCart ShoppingCart { get; set; }
        public virtual Product Product { get; set; }
    }
}
