//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buyer
    {
        public Buyer()
        {
            this.Role = "покупатель";
        }

    public System.Guid Id { get; set; }
        public string Role { get; set; }
        public string Login { get; set; }
        public string PasswordHash { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string PhoneNumber { get; set; }
        public string Adress { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public System.DateTime DateOfRegister { get; set; }
        public System.Guid ShoppingCartId { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
        public virtual ShoppingCart ShoppingCart { get; set; }
    }
}
