//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItem = new HashSet<OrderItem>();
            this.Id = System.Guid.NewGuid();
            this.DateOfOrder = DateTime.Now;
        }
    
        public System.Guid Id { get; set; }
        public System.Guid BuyerId { get; set; }
        public System.DateTime DateOfOrder { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual ICollection<OrderItem> OrderItem { get; set; }
    }
}
