//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public Shop()
        {
            this.Product = new HashSet<Product>();        
            this.Name = "Super Game Store";
            this.Description = "Лучший магазин на просторах интерента. Даже сам Гейб Ньюэлл завидует ему";
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.Guid ProductId { get; set; }
    
        public virtual ICollection<Product> Product { get; set; }
    }
}
